version: '3.8'

services:
  # Frontend
  web:
    image: jitsi/web:stable-7882
    container_name: web
    restart: unless-stopped
    ports:
      - "9443:443"
    environment:
      - DISABLE_HTTPS=0
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - XMPP_DOMAIN=${XMPP_DOMAIN}
    networks:
      meet.jitsi:
        aliases:
          - meet.jitsi
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  # XMPP server
  prosody:
    image: jitsi/prosody:stable-7882
    container_name: prosody
    restart: unless-stopped
    environment:
      - XMPP_DOMAIN=${XMPP_DOMAIN}
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
    networks:
      meet.jitsi:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  # Focus component
  jicofo:
    image: jitsi/jicofo:stable-7882
    container_name: jicofo
    restart: unless-stopped
    environment:
      - XMPP_DOMAIN=${XMPP_DOMAIN}
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
    depends_on:
      - prosody
    networks:
      meet.jitsi:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  # Video bridge
  jvb:
    image: jitsi/jvb:stable-7882
    container_name: jvb
    restart: unless-stopped
    ports:
      - "10000-10200:10000-10200/udp"
    environment:
      - XMPP_SERVER=prosody
      - XMPP_DOMAIN=${XMPP_DOMAIN}
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_STUN_SERVERS=${JVB_STUN_SERVERS}
    depends_on:
      - prosody
    networks:
      meet.jitsi:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 512M

networks:
  meet.jitsi:
    name: meet.jitsi